import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home - Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <header style={
        {
          color: 'white',
          fontSize: '20px',
          textAlign: 'center',
          backgroundColor: 'red'
        }
      }>
        <h1>My App</h1>
      </header>
        {children}
        <footer style={
        {
          color: 'white',
          fontSize: '20px',
          textAlign: 'center',
          backgroundColor: 'red'
        }
      }> 
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
