export const metadata = {
    // title: "Blog",
    title:{
        absolute:"Blog",
    },
    description: "Generated by create next app",
  };
export default function BlogLayout({children}) {
    return (
        <>
            <h3>Blog  Layout</h3>
            {children}
            
        </>
    );
}